### ISSUE TITLE
Consolidate crates under syntax-highlighter

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph-public-snapshot#59792]
We currently have the following dependency structure (generated via `cargo depgraph`)

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/92af52a2-07ca-4819-8cd7-090a8cf807c0)

<details>
<summary> GraphViz code </summary>

```graphviz
digraph {
    graph [fontname = "Handlee"];
    node [fontname = "Handlee"];
    edge [fontname = "Handlee"];

    0 [ label = "sg-syntax" shape = box]
    1 [ label = "scip-syntax" shape = box]
    2 [ label = "scip-macros" shape = box, color = green3]
    3 [ label = "scip-treesitter" shape = box]
    4 [ label = "scip-treesitter-languages" shape = box]
    5 [ label = "scip-treesitter-cli" shape = box]
    6 [ label = "syntect_server" shape = box]
    0 -> 1 [ ]
    0 -> 3 [ ]
    0 -> 4 [ ]
    1 -> 2 [ color = green3]
    1 -> 3 [ ]
    1 -> 4 [ ]
    4 -> 2 [ color = green3]
    5 -> 1 [ ]
    5 -> 3 [ ]
    5 -> 4 [ ]
    6 -> 1 [ ]
    6 -> 3 [ ]
    6 -> 4 [ ]
    6 -> 0 [ ]
}
```

</details>

- `syntect_server` is the main entrypoint for highlighting:
  - Uses Tree-sitter for highlighting in some cases
  - Is different from `syntax-highlighter` which is the name of the overall service/Docker image (however, there is technically `http-server-stabilizer` sitting in front of it).
  - It also provides locals data
  - Proposal: Rename this to `syntax-server` (similar to `gitserver`).
- `scip-treesitter` is a library and doesn't have code for actually producing a SCIP index using Tree-sitter (unlike other `scip-*` indexers)
  - It has some utilities related to scip, unrelated to Tree-sitter.
      - Proposal: These can be folded back into the official SCIP bindings or into `scip-syntax` (or future `syntax-analysis`).
  -  Some utilities related to Tree-sitter.
      - Proposal: Fold this into `scip-syntax` (or future `syntax-analysis`).
        - [x] https://github.com/sourcegraph/sourcegraph/pull/59862
- `sg-syntax` has a bunch of highlighting related code that bridges between scip-syntax and syntax-highlighter.
  - Proposal: Remove this crate, move highlighting code to scip-syntax, and server-related code to syntax-server.
    - [x] https://github.com/sourcegraph/sourcegraph/pull/59890
    - [x] Move web server related code to syntax-server https://github.com/sourcegraph/sourcegraph/pull/60039
- `scip-treesitter-languages` is a single point of entry for the various language grammars, and it has a bit of code related to highlighting which is unrelated. It doesn't really generate a SCIP index.
  - Proposal: Rename this to `tree-sitter-all-languages`. Move highlighting code to separate crate.
    - [x] https://github.com/sourcegraph/sourcegraph/pull/59857
- `scip-syntax` contains the logic for handling queries and producing SCIP data.
  - Proposal: Rename this to `syntax-analysis`. It's not an indexer, so avoid the `scip-*` prefix. The highlighting stuff can be moved from `scip-treesitter-languages` to this crate.
    - [x] https://github.com/sourcegraph/sourcegraph/pull/59895
    - [x] Move highlighting related code from tree-sitter-all-languages stuff to this crate. https://github.com/sourcegraph/sourcegraph/pull/59904
- `scip-treesitter-cli` produces an index based on Tree-sitter/syntactic data.
  - Proposal: Rename to `scip-syntax` because it's actually producing SCIP data.
      - [x] https://github.com/sourcegraph/sourcegraph/pull/60077
- `scip-macros` contains doesn't have anything to do with SCIP as such.
  - It seems like the implementation of this proc macro can be removed by just listing the directory names for each language, plus a simple rules-based macro.
  - Proposal: Get rid of this crate.
    - [x] https://github.com/sourcegraph/sourcegraph/pull/59850

New overall proposed diagram.

![CleanShot 2024-01-24 at 20 57 04@2x](https://github.com/sourcegraph/sourcegraph/assets/93103176/9ec90937-8c39-46ef-8808-99576cf5641c)

<details>
<summary>GraphViz code</summary>

```graphviz
digraph {
    graph [fontname = "Handlee"];
    node [fontname = "Handlee"];
    edge [fontname = "Handlee"];

    0 [ label = "tree-sitter-all-languages" shape = box]
    1 [ label = "syntax-analysis" shape = box]
    2 [ label = "scip-syntax (bin)" shape = box]
    3 [ label = "syntax-server (bin)" shape = box]

    2 -> 0
    1 -> 0
    3 -> 1
    3 -> 0
    2 -> 1
}
```
</details>

**Comment by kritzcreek** [comment]
> `scip-macros` Proposal: Get rid of this crate.

❤️ 

I'm missing the evaluation code in here. It's SCIP specific, so would you say it stays in `scip-syntax`?

**Comment by varungandhi-src** [comment]
Evaluation code needs to go in `syntax-analysis` (= old `scip-syntax`) per the diagram, because the locals information is needed by `syntax-server` (= old `syntax-highlighter`).

**Comment by kritzcreek** [comment]
Sorry, I don't understand how that would be related to the locals information. I'm talking about `docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/evaluate.rs`

**Comment by varungandhi-src** [comment]
Serves me right for replying around 1am. 😪 You're right, they're two different things. The evaluation code is currently in `scip-treesitter-cli`, so it would stay in the same crate (only the crate would be renamed to `scip-syntax`).
