### ISSUE TITLE
Public repos not showing up on SG

### ISSUE THREAD

**Issue by sjain-stanford** [sourcegraph/sourcegraph-public-snapshot#64543]
I'm unable to search these repos on SourceGraph today:

https://sourcegraph.com/github.com/llvm/torch-mlir
https://sourcegraph.com/github.com/llvm/llvm-project

![image](https://github.com/user-attachments/assets/1414a6b3-f861-43ed-936e-3369f6dd6f73)

**Comment by varungandhi-src** [comment]
We had an incident earlier where a bunch of repos went missing (https://sourcegraphstatus.com/ - Sep 3), this is fixed now.
